name: bitset
version: 0.0.1
author: Keishi Hattori <keishi.hattori@gmail.com>
description: BitSet class.
homepage: https://github.com/keishi/bitset
dev_dependencies:
  benchmark_harness: any
  unittest: any
